### ISSUE TITLE
Doctor's WorkPlan update

### ISSUE THREAD

**Issue by MendelDamian** [MendelDamian/virtual-clinic-api#1]
- [x] allow multiple schedules per one day
- [x] validate for schedule overlapping
- [x] update endpoint for listing available appointments
